# SPDX-FileCopyrightText: 2026 CoreWeave, Inc.
# SPDX-License-Identifier: Apache-2.0
# SPDX-PackageName: senpai

[project]
name = "senpai"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "numpy",
    "PyYAML",
    "torch==2.11.0",
    "torch_geometric",
    "einops",
    "timm",
    "rich",
    "python-dotenv",
    "simple-parsing",
    "wandb",
    "weave",
    "tqdm",
    "matplotlib",
    "openhands-sdk==1.28.1",
    "openhands-tools==1.28.1",
]

[tool.setuptools.packages.find]
exclude = ["k8s*", "target*", "tests*"]

[project.optional-dependencies]
dev = [
    "ipython",
    "jupyter",
    "pytest",
]
